const Strings = {
  API_ALL_USERS: "/admin/all-users",
  API_BAN_USER: "/admin/ban/",
  API_UNBAN_USER: "/admin/unban-user/",

  ERROR_FAILED_FETCH_USERS: "Failed to fetch users",
  ERROR_UNAUTHORIZED: "Unauthorized",
  ERROR_FAILED_BAN_USER: "Failed to ban user",
  ERROR_FAILED_UNBAN_USER: "Failed to unban user",

  USERS_LIST_TITLE: "Users List",
  LOADING_USERS: "Loading users...",
  ERROR_PREFIX: "Error: ",
  NO_USERS_FOUND: "No users found.",
  EMAIL_LABEL: "Email:",
  NAME_LABEL: "Name:",
  FOLLOWERS_LABEL: "Followers:",
  FOLLOWING_LABEL: "Following:",
  STATUS_LABEL: "Status:",
  STATUS_BANNED: "Banned",
  STATUS_ACTIVE: "Active",
  REASON_LABEL: "Reason:",
  BAN_USER: "Ban User",
  UNBAN_USER: "Unban User",
  BANNING: "Banning...",
  UNBANNING: "Unbanning...",
  PREVIOUS: "Previous",
  NEXT: "Next",
  BAN_USER_PROMPT: "Ban User: ",
  REASON_FOR_BAN: "Reason for Ban:",
  BAN_REASON_PLACEHOLDER:
    "Enter ban reason (e.g., Violation of community guidelines)",
  CONFIRM: "Confirm",
  CANCEL: "Cancel",

  ADMIN_LOGIN_TITLE: "Admin Login",
  EMAIL_INPUT_LABEL: "Email:",
  EMAIL_INPUT_PLACEHOLDER: "Enter email",
  PASSWORD_INPUT_LABEL: "Password:",
  PASSWORD_INPUT_PLACEHOLDER: "Enter password",
  LOGGING_IN: "Logging in...",
  LOGIN: "Login",
  CLEAR_ERROR: "Clear Error",
  LOGIN_SUCCESS: "Login successful! Access token received.",

  NAVBAR_TITLE: "Instagram",
  NAVBAR_USERS: "Users",
  NAVBAR_ALL_USERS: "all users",
  NAVBAR_SEARCH: "Search",
  NAVBAR_USERS_SHORT: "Users",
  NAVBAR_ALL_POST: "All Post",
  NAVBAR_FOLLOWS: "Follows",
  NAVBAR_AUTH: "Auth",
  NAVBAR_AUTH_SHORT: "authen..",
  NAVBAR_HELP: "Help",
  NAVBAR_MORE: "More",
};

export default Strings;
